### ISSUE TITLE
LLaMA_Analysis missing in the code

### ISSUE THREAD

**Issue by sheryc** [TaiMingLu/know-dont-tell#1]
Hi, I noticed that LLaMA_Analysis mentioned in https://github.com/TaiMingLu/know-dont-tell/blob/5664112132192c629808541358dea739e85cb7ee/code/forward/inference_and_save_kv.py#L1 is missing. Could you please update the code to include this class?

**Comment by TaiMingLu** [comment]
Update! Thank you for pointing this out.
